version: "2"
services:
  app:
    image: singularitiesorg/song-pot
    ports:
      - "3000:80"
    links:
      - mongo
    environment:
      - MONGO_URL=mongodb://mongo/song-pot
      - ROOT_URL=http://localhost:3000
      - MAIL_URL=smtp://some.mailserver.com:25

    depends_on:
      - mongo
    restart: on-failure
  mongo:
    image: mongo:latest
    restart: on-failure
